input: touchscreen: focaltech touch: Fix compilation error
It fixes the issue with the following logs on 5.10 kernel.

  /opt/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-ld: drivers/built-in.a: member drivers/input/touchscreen/focaltech_touch/focaltech_test in archive is not an object
  Makefile:1284: recipe for target 'vmlinux' failed
  make: *** [vmlinux] Error 1
   MAKE KERNEL IMAGE FAILED.

It fixes the issue with the following logs on 6.1 kernel.

aarch64-linux-gnu-ar: drivers/input/touchscreen/focaltech_touch/focaltech_test/: file format not recognized
make[6]: *** [scripts/Makefile.build:425: drivers/input/touchscreen/focaltech_touch/built-in.a] Error 123.

Signed-off-by: Stephen <stephen@vamrs.com>
Signed-off-by: Feng Zhang <feng@radxa.com>
(cherry picked from commit bd09ce30be5157b3070425719da2675fb60c0e02)
Signed-off-by: Joshua Riek <jjriek@verizon.net>